version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env

    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

#  migrate:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: migrate_app
#    command: sh -c "alembic upgrade head"
#    environment:
#      - DB_URL=postgresql+asyncpg://postgres:wer255678@host.docker.internal:5432/db_ToDo
#    volumes:
#      - ./app:/app
#    depends_on:
#      - db

  web:
    image: app_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_web
    environment:
      - DB_URL=postgresql+asyncpg://postgres:wer255678@host.docker.internal:5432/db_ToDo
    ports:
      - '9000:8000'
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn app.main:main_app --host 0.0.0.0 --port 8000"

volumes:
  db_data:

