"""add cascade='all, delete-orphan')

Revision ID: ccad3ed2b17f
Revises: fbe3c6789c75
Create Date: 2024-08-05 13:44:26.830733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccad3ed2b17f'
down_revision: Union[str, None] = 'fbe3c6789c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taskpermissions_task_id_fkey', 'taskpermissions', type_='foreignkey')
    op.create_foreign_key(None, 'taskpermissions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskpermissions', type_='foreignkey')
    op.create_foreign_key('taskpermissions_task_id_fkey', 'taskpermissions', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
